export const opportunityFixtureStates = [
  {
    key: "strong",
    label: "强Opportunity",
    title: "首次配置复杂形成可验证的产品缺口",
    readiness: "validation_ready",
    evidence: "3 个独立来源 · 2 个平台",
    detail: "多个用户描述了相似的配置摩擦；营销转载已合并，仍保留原始证据。",
  },
  {
    key: "weak",
    label: "弱Opportunity",
    title: "单一营销来源提到一个新需求",
    readiness: "needs_more_evidence",
    evidence: "1 个来源 · 转载风险高",
    detail: "只进入证据建设，不生成商业结论。",
  },
  {
    key: "counterevidence",
    label: "Counterevidence",
    title: "用户痛点可能被熟练用户样本夸大",
    readiness: "review_ready",
    evidence: "2 个支持来源 · 1 条反向证据",
    detail: "反向证据与支持证据并列展示，等待用户判断是否继续验证。",
  },
  {
    key: "content",
    label: "Content Opportunity",
    title: "用户困惑但现有内容没有回答清楚",
    readiness: "review_ready",
    evidence: "重复提问 · 内容缺口已绑定Evidence",
    detail: "只提供受众、内容缺口和三个证据驱动的角度，不伪装成热点。",
  },
  {
    key: "validation",
    label: "Validation Plan",
    title: "先验证问题频率，再扩大研究",
    readiness: "ready",
    evidence: "最小验证动作 · 成功/失败标准",
    detail: "用户确认后才会创建独立Follow-up Research。",
  },
  {
    key: "validation-complete",
    label: "Validation Complete",
    title: "验证结果支持部分假设",
    readiness: "partially_supported",
    evidence: "Opportunity v2 · 历史版本保留",
    detail: "结果不会覆盖原判断，下一步由用户决定。",
  },
  {
    key: "action-outcome",
    label: "Action & Outcome",
    title: "行动完成，Outcome回到长期记忆",
    readiness: "memory_updated",
    evidence: "用户手工记录 · 可撤回历史",
    detail: "行动必须先批准；Outcome不等于AI自行执行现实世界动作。",
  },
  {
    key: "empty",
    label: "No Opportunity",
    title: "目前还没有足够证据形成值得行动的机会",
    readiness: "no_opportunity_identified",
    evidence: "不强行生成",
    detail: "继续研究、运行监控，或处理发现后再重新判断。",
  },
] as const;
